# Generated by Django 5.2.10 on 2026-02-17 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_image", models.ImageField(upload_to="uploads/%Y/%m/")),
                (
                    "languages",
                    models.JSONField(
                        default=list,
                        help_text='List of language codes, e.g. ["fa", "en"]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("generated_html", models.TextField(blank=True, default="")),
                ("generated_css", models.TextField(blank=True, default="")),
                ("combined_output", models.TextField(blank=True, default="")),
                ("analysis_metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
